### ISSUE TITLE
第三章  3.8 ROS人机交互软件介绍 寻求好的人机交互例子

### ISSUE THREAD

**Issue by Dale-Git** [lovelyyoshino/ROS-ROS2-BOOKS#1]
本书第三章，3.8节包含：
3.8　ROS人机交互软件介绍 168
3.8.1　ROS与QT的交互 169
3.8.2　ROS与Web的交互——rosbridge 170
3.8.3　ROS与Java的交互——rosjava 171

不知道可否提供一些例子作为参考（如果能写有如何部署那就更好了）。

非常感谢！

**Comment by lovelyyoshino** [comment]
您需要哪些，可以联系作者交流
